### PR TITLE
Support universal wheels

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by Byron** [comment]
Thank you very much ! I hope getting wheels support can be as trivial for smmap and gitpython too.

**Comment by graingert** [comment]
Already done https://github.com/gitpython-developers/smmap/blob/master/setup.cfg#L2

they all just need a new release with `python3 setup.py sdist bdist_wheel register upload`

**Comment by Byron** [comment]
Thanks for the hint ! Unfortunately, this command-line `pip3 install wheel && python3 setup.py sdist bdist_wheel upload` fails with 
```
Requirement already satisfied (use --upgrade to upgrade): wheel in /usr/local/lib/python3.5/site-packages
/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
```

It's a bit odd, and I have no explanation for that :/.

**Comment by graingert** [comment]
Ah I know the issue. Please await a PR...

**Comment by graingert** [comment]
python3 -m venv /tmp/gitpython/
source /tmp/gitpython/bin/activate
pip install -U pip setuptools wheel
python setup.py sdist bdist_wheel register upload

On 11 Sep 2016 17:44, "Sebastian Thiel" <notifications@github.com> wrote:

Thanks for the hint ! Unfortunately, this command-line pip3 install wheel
&& python3 setup.py sdist bdist_wheel upload fails with

Requirement already satisfied (use --upgrade to upgrade): wheel in
/usr/local/lib/python3.5/site-packages
/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py:261:
UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py:261:
UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'

It's a bit odd, and I have no explanation for that :/.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gitpython-developers/gitdb/pull/29#issuecomment-246190003>,
or mute the thread

**Comment by Byron** [comment]
Thanks again !
Even after creating the virtualenv, I am seeing the same issue:
```
$ /tmp/gitpython/bin/python ./setup.py sdist bdist_wheel register upload
/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
```
Maybe it's something odd with my system installation, which still seems to be part of the mix.

**Comment by ankostis** [comment]
@Byron I dont' know what's the status of it, but actually [the "official" guide does not recommend this command](https://packaging.python.org/distributing/#register-your-project).
Use [*twine* tool](https://pypi.python.org/pypi/twine) instead.

**Comment by graingert** [comment]
You don't need to bother with twine on python3

**Comment by ankostis** [comment]
@graingert wrote:
> You don't need to bother with twine on python3

Would you mind explaining a bit more on that point?
And possibly provide an example command for @byron on #511?

**Comment by graingert** [comment]
Ah sorry I thought this was a different thread. This package can't do
simple universal wheels unless it drops the c extensions

On 2 Oct 2016 22:05, "Kostis Anagnostopoulos" <notifications@github.com>
wrote:

@graingert <https://github.com/graingert> wrote:

You don't need to bother with twine on python3

Would you mind explaining a bit more on that point?
And possibly provide an example command for @byron
<https://github.com/byron> on #511?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/gitpython-developers/gitdb/pull/29#issuecomment-250996005>,
or mute the thread

**Comment by ankostis** [comment]
But there are no C extensions, are they?

**Comment by graingert** [comment]
I thought there was...

**Comment by kevin-brown** [comment]
> But there are no C extensions, are they?

There are

https://github.com/gitpython-developers/gitdb/blob/847a21ebf0f20f708b1d879f7f8e865ae9d64817/setup.py#L92

**Comment by ankostis** [comment]
Thank you, I'm involved in this project the last days so I miss a lost of stuff.

I have not managed to build them - trying also in Appveyor without success.
Anyway, they semm to be optional, so *wheels* are universal.
Using *twine* should be the safest option to deply them into *PyPi*.

And possibly they can be systematically deployed by Appveyor with a setup like this:

```YAML
environment:
  PYPI_USER: "FOO"
  PYPI_PSWD:
    # See https://www.appveyor.com/docs/build-configuration/#secure-variables
    secure: <paste-your-encrypted-value>

#... regular build here

on_success:
  - ps: >-
      $cmtid = git rev-parse HEAD
      if (git describe --exact-match $cmtid) {
        twine upload -u PYPI_USER -p PYPI_PSWD dist/*
      }
````

**Comment by ankostis** [comment]
Actually I never really liked *git modules* for managing project dependencies - they complicate things needlesly.  They may have been useful back when python packaging was imature and a major cause of hurdles.  Now, eating our wn dogfood, pushng wheels into *PyPi* and re-using them aterwards should be a better alternative.

I'm interesting to here any feedback on a change along these lines (drop submodules from *gitdb* and *gitpython* and depend on regulat python wheels.

**Comment by graingert** [comment]
It would be good to extract the optional c extension into an optional,
separate, -fast package

**Comment by ankostis** [comment]
Any PR is welcome.

**Pull request merged**
