### PR TITLE
Bumped smmap upper bound

### LINKED ISSUE #67: Update requirements for smmap
[`smmap`](https://pypi.org/project/smmap/) cut a release for version 4.0.0 a few hours ago, but the [`requirements.txt`](https://github.com/gitpython-developers/gitdb/blob/master/requirements.txt) specifies `smmap>=3.0.1,<4`. To avoid dependency snares for downstream packages this upper bound should be removed.

### PR DESCRIPTION
**Pull request by tmcclintock**
Closes #67 

Tests passed locally.

### CODE REVIEW

**Review by Byron — CHANGES_REQUESTED** [review]
Thanks a bunch!

Could you also increase the gitdb version number to something you find suitable for such a change?
My problem is that I don't really know what's going on and why things are breaking down as they do, originally @Harmon758 did tremendous work to assure of that.

**Review by Harmon758 — APPROVED** [review]
@Byron A patch version bump should be fine for this.

**Comment by Byron** [comment]
Thanks, @Harmon758 , I just published v4.0.6, unfortunately along with 4.0.5 as that one was apparently still lying around locally. It's interesting to see how pypi allows overwriting/altering already published versions. Let's hope that doesn't break things.

```
View at:
https://pypi.org/project/gitdb/4.0.6/
https://pypi.org/project/gitdb/4.0.5/
```

**Comment by Harmon758** [comment]
v4.0.5 was already released on May 4, 2020, and you can't alter or overwrite existing releases, so I don't think anything happened with that version.

**Pull request merged**
