### PR TITLE
Windows fixes for leaking file handles #37

### PR DESCRIPTION
**Pull request by stuertz**
Fix for https://github.com/gitpython-developers/gitdb/issues/37.
All tests run also on windows now.

### CODE REVIEW

**Comment by Byron-TW** [comment]
@stuertz Thanks for your contribution! Just as a word of warning you should know that I am way behind my GitPython related maintenance work. A lot piled up, and this PR will eventually be handled. Thanks for your understanding.

**Comment by ankostis** [comment]
My +1 gratitude to you @stuertz for this, thanks.

**Comment by ankostis** [comment]
On me, for not forgetting to check if this PR also fixes some more "hidden" leak-errors in Gitpython (see gitpython-developers/GitPython#525).

**Comment by Byron** [comment]
@ankostis Thanks for looking into this. I would offer some help, but have long lost track of what it means to get it to work on windows - sorry for that. Please feel free to merge whenever you think the PR is ready.
@stuertz Sorry again for taking so much time - it's not a sign of depreciation of this PR.

**Comment by stuertz** [comment]
@Byron: I understand and accept that you are behind. But this at least makes the code usable on windows again and IMHO does not brake anything :-). Maybe the solution is currently not ideal, but helps the windows users a lot. So please consider to just merge and release the version :-)

**Comment by Byron** [comment]
@stuertz Thanks for all the fixes, and sorry again for not following up on this one. I am currently working to catch up on GitPython/GitDB, and a new release should be a result of this.

**Pull request merged**
